services:
  - type: web
    name: parking-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: ""          # Dockerfile handles build
    startCommand: ""          # Dockerfile handles run
    healthCheckPath: "/actuator/health"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: PHONEPE_CLIENT_ID
        value: SU250917979468
      - key: PHONEPE_CLIENT_SECRET
        value: e4e2904621b5e66f6
      - key: PHONEPE_CLIENT_VERSION
        value: 1
      - key: PHONEPE_PROD_TOKEN_URL
        value: https://api.phonepe.com/apis/identity-manager/v1/oauth/token
      - key: PHONEPE_PROD_ORDER_URL
        value: https://api.phonepe.com/apis/pg/checkout/v2/sdk/order
      - key: PHONEPE_PROD_STATUS_URL
        value: https://api.phonepe.com/apis/pg/checkout/v2/order

      - key: SPRING_DATASOURCE_URL
        value: postgresql://parkingdb_gcgw_user:bQElmzgYaA0XlPGLm24fybIV9xjaD9MX@dpg-d36g4j2dbo4c73dq9g10-a/parkingdb_gcgw
      - key: SPRING_DATASOURCE_USERNAME
        value: parkingdb_gcgw_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: bQElmzgYaA0XlPGLm24fybIV9xjaD9MX
