services:
  - type: web
    name: parking-backend
    env: docker
    plan: free
    branch: main
    autoDeploy: true
    buildCommand: ""          # Dockerfile handles build
    startCommand: ""          # Dockerfile handles run
    healthCheckPath: "/actuator/health"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
